CREATE DATABASE IF NOT EXISTS tasks CHARSET utf8mb4;
USE tasks;

CREATE TABLE IF NOT EXISTS category(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
category_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS rights(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
rights_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS `account`(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
lastname VARCHAR(50) NOT NULL,
firstname VARCHAR(50) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
`password` VARCHAR(100) NOT NULL,
image VARCHAR(255) NOT NULL,
rights_id INT NOT NULL,
CONSTRAINT fk_to_assign_rights
FOREIGN KEY(rights_id)
REFERENCES rights(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS task(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
title VARCHAR(50) NOT NULL,
`description` VARCHAR(255) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated_at DATETIME,
finish_on DATETIME NOT NULL,
`status` BOOLEAN DEFAULT true,
`repeat` VARCHAR(50),
account_id INT NOT NULL,
CONSTRAINT fk_to_add_account
FOREIGN KEY(account_id)
REFERENCES `account`(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS task_category(
task_id INT,
category_id INT,
PRIMARY KEY(task_id, category_id),
CONSTRAINT fk_to_complete_category
FOREIGN KEY(category_id)
REFERENCES category(id) ON DELETE CASCADE,
CONSTRAINT fk_to_complete_task
FOREIGN KEY(task_id)
REFERENCES task(id) ON DELETE CASCADE
);